### ISSUE TITLE
Firefox problem

### ISSUE THREAD

**Issue by rickybrce** [mjfisheruk/jquery.pan#2] opened 2016-06-21 09:18 UTC
Hello,

The pan is not working on firefox. Any idea how to fix it?
Thanks

**Comment by mjfisheruk** [comment] 2020-01-25 15:26
Hi @rickybrce ,

Sorry for this response taking almost four years; I've been away from Github for a while. This plugin was tested on Firefox, Chrome and IE at the time, and appeared to work just fine in those browsers.

I'm provisionally going to close this issue, as it's certainly working on Firefox as I'm testing now, and I can't imagine you'd be able to remember the browser version now so much time has passed.

However, if the problem is still reproducible for you, please respond and I'll reopen and we can work it out together!

Thanks

**Closed as completed by mjfisheruk** 2020-01-25 15:26 UTC
